services:
  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-qr_bot}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-change_me}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672" # необязательно: веб-интерфейс RabbitMQ

  postgres:
    image: postgres:17
    container_name: database
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tg_bot:
    build:
      context: .
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./files:/app/files
    environment:
      - FILES_DIR=/app/files/checks
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-qr_bot}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-change_me}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}

  qr_worker:
    build:
      context: .
    container_name: qr_worker
    restart: always
    entrypoint: [ "python", "-u", "qr_worker.py" ]
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-qr_bot}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-change_me}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
volumes:
  postgres_data:
  rabbitmq_data:
